module.exports = {
    anomalyUpdate:          require('./anomalyUpdate'),
    asteroidUpdate:         require('./asteroidUpdate'),
    beamFired:              require('./beamFired'),
    blackHoleUpdate:        require('./blackHoleUpdate'),
    cloakFlash:             require('./cloakFlash'),
    destroyObject:          require('./destroyObject'),
    droneUpdate:            require('./droneUpdate'),
    engineeringUpdate:      require('./engineeringUpdate'),
    intel:                  require('./intel'),
    mineUpdate:             require('./mineUpdate'),
    monsterUpdate:          require('./monsterUpdate'),
    nebulaUpdate:           require('./nebulaUpdate'),
    npcUpdate:              require('./npcUpdate'),
    playerUpdate:           require('./playerUpdate'),
    soundEffect:            require('./soundEffect'),
    stationUpdate:          require('./stationUpdate'),
    torpedoUpdate:          require('./torpedoUpdate'),
    unknownObjectUpdate:    require('./unknownObjectUpdate'),
    weaponsUpdate:          require('./weaponsUpdate'),
    whaleUpdate:            require('./whaleUpdate')
};